Update Selenium to v4
featurist/coypu pull request #225
Opened 2021-11-06 18:07 UTC by slang25

This PR contains 3 changes:
- Updating the `Selenium.WebDriver` dependency to `4.0.1`
- Changes test projects to .NET 6
- Get the test passing on macOS, this includes changing the self-hosted server to aspnetcore

2021-11-25 12:56 UTC, petersladek commented
@obstar Any plans when this will be merged?

2022-03-04 20:16 UTC, mhlavacek commented
Any updates on this?  I'm waiting to be able to update to selenium webdriver 4.x

2022-03-04 20:40 UTC, slang25 commented
That'll be a question for @obstar, would be good to know if there is an intention to merge. No pressure here, just nice to have from my perspective

2022-03-08 00:44 UTC, sbowler commented
I'm pretty sure there's a runtime issue taking screenshots that needs to be adjusted with this move to .NET 6. See https://github.com/SeleniumHQ/selenium/issues/8760 for more details on what I'm running into and possible solutions. I could be wrong, but I think this should be adjusted here.

2022-04-07 08:55 UTC, ben-soler commented
Any updates on this PR?

2022-07-13 09:58 UTC, DDSGooch commented
When will this be merged? Is there any reason this can't be done now. We'd really appreciate this update and I'm happy to do some testing on this. Thanks

2023-03-28 13:15 UTC, adiel commented
Hi! Just checking back in on this project and seems like nobody maintaining it any more.

Any volunteers from this thread? I know a lot of projects are relying on it still.

2023-05-24 20:41 UTC, sbowler requested changes
I would also suggest updating the NUnit project to net6.0 instead of net45. At this point it would probably be good to update some of the other dependencies as well like browser drivers for example.

2023-05-25 13:40 UTC, sbowler commented on src/Coypu.Drivers.Tests/DriverSpecs.cs
> +    public static SelfHostedSite TestSite;
I was using visual studio 2022

2023-06-01 16:07 UTC, sbowler commented
@slang25 I think I've highlighted the main issues I found. Just wondering if you'll be able to update this and an idea on the timeframe?

2023-06-01 16:35 UTC, slang25 commented
I'll have a look over the weekend, you are right, it's totally broken, I blame past me 😆

2023-06-01 21:32 UTC, obstar commented
@ijabit tbh the best alternative is playwright a lot faster and user friendly than selenium 🤷‍♂️

2023-06-01 21:35 UTC, ijabit commented
> 

Thanks! I think I'm locked in to Selenium though due to organizational choices

2023-06-01 21:36 UTC, adiel commented
For sure.

Although a Coypu driver for Playwright should be pretty trivial and best of
both worlds if you ask me. It still has all the semantic finder and wait
issues that this project tackles.

I'm planning to do this in a few weeks time when I have some time off
coming up.

On Thu, 1 Jun 2023 at 22:33, Jakub Obstarczyk ***@***.***>
wrote:

> @ijabit <https://github.com/ijabit> tbh the best alternative is
> playwright a lot faster and user friendly than selenium 🤷‍♂️
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/featurist/coypu/pull/225#issuecomment-1572817198>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAASTJECT63T2M55CTJWLUTXJEDBHANCNFSM5HP3FOPQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-06-06 22:35 UTC, ijabit commented
I thought Coypu was tied to Selenium, interesting that you might be able to hook it up to Playwright

2023-06-19 16:10 UTC, sbowler commented
@slang25 If you don't have time to work on this, let me know and I can finish it up and submit a PR if you need.

2023-06-19 16:29 UTC, slang25 commented
I'm not sure I'm going to get around to it 😔

2023-06-19 16:36 UTC, adiel commented
I did get this branch working the other day - it was basically just the
errors that were pointed out on the pull request. Then I had to update a
bunch of references and language settings - I didn't really know what I was
doing not having run dotnet for so many years. Managed to get it compiling
though on my Mac, and installed Playwright ok and made the first steps
towards a Playwright driver. Hoping to get time to finish it in a couple of
weeks time.

I'll push what I did (minus the playwright stuff) later when I get in and
maybe you can give it a run and see if I did anything stupid Stacy?

On Mon, 19 Jun 2023 at 17:29, Stuart Lang ***@***.***> wrote:

> I'm not sure I'm going to get around to it 😔
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/featurist/coypu/pull/225#issuecomment-1597464477>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAASTJB7PICFBCFOLB2A4CTXMB47VANCNFSM5HP3FOPQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-06-30 18:01 UTC, ijabit commented
Any updates on this one?

2023-07-05 18:19 UTC, sbowler commented
Closing in favor of https://github.com/featurist/coypu/pull/228

2023-07-05 18:19 UTC, closed without merging

2023-12-09 16:24 UTC, adiel commented
> I thought Coypu was tied to Selenium, interesting that you might be able to hook it up to Playwright

https://github.com/featurist/coypu/pull/231